name: CI
run-name: ${{ github.event.inputs.name }}

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Manual trigger for release
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        default: 'snapshot'
      text:
        description: 'Release description'
        required: true
        default: 'Snapshot release of the main branch'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
            version: 6.8.3
            use-official: false
            host: windows
            target: desktop
            arch: win64_mingw
            tools: 'tools_mingw1310' # Install latest mingw for c++20
            add-tools-to-path: true # Prefix path with installed tools, shadowing runner's builtin g++ with Qt more recent version
            cache: true
      - name: Configure
        run: |
          make configure
      - name: Test
        run: |
          make test
      - name: Install
        run: |
          mkdir out
          make install INSTALL_ROOT=out
          7z a newbase.zip ./out/*
      - name: Release
        # Only if manually triggered
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.name }}
          tag_name: ${{ github.event.inputs.name }}
          target_commitish: main
          body: ${{ github.event.inputs.text }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            newbase.zip